version: "3.9"
services:

  postgresdb:
    image: postgres:14.5-bullseye
    container_name: postgres_container
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/docker-entrypoint-initdb.d
    networks:
      - backend
    ports:
      - "5432:5432"

  app:
    build:
      dockerfile: Dockerfile
    container_name: seamless_container
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgresdb
    networks:
      - backend
    ports:
      - "8080:8080"

networks:
  backend:
    driver: bridge